#!/bin/bash

if ( cd "${srcdir}"/"${_winesrcdir}" && git merge-base --is-ancestor 765ea3470ad96dfcbd8ce4c239225206ea41be8a HEAD ); then
  warning "Hotfix: WoW64 builtin so."
  _hotfixes+=("$_where"/wine-tkg-patches/hotfixes/wow64_builtin_so/wow64_builtin_so)
fi